url: 'https://cloutsights.com'
twitter-username: Cloutsights

title: Cloutsights
description: |
  A macOS menu bar app to track your favorite creator coins.

incremental: true

defaults:
  -
    scope:
      path: _posts/*
    values:
      layout: post

date_format: '%b %d, %Y'
permalink: pretty

# Build settings
sass:
  sass_dir: _sass
  style: compressed

include: ['_pages']

plugins:
  - 'jekyll-autoprefixer'
  - 'jekyll-minifier'

exclude:
  - Gemfile
  - Gemfile.lock